import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { toast, ToastContainer } from "react-toastify";
import AddBookContainer from "../containers/addBookContainer";
import { useStore } from "../store";

const AddBookPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Library Managerment</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AddBookContainer />
    </>
  );
};

export default AddBookPage;
